theme: jekyll-theme-minimal
title: [Guanqun Mu]
description: [Welcome to Guanqun Mu's homepage]
logo: [<img src="https://github.com/GuanQunMu/IonTrap-WIPM/blob/master/Pictures/GUI1.0.png" width="400"/>]
